---
title: "Student_performance"
author: "*Buthaina Alshareef*"
date: "*21-10-2020*"
output:
  html_document:
   toc: true
   toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
library(DT)
#library(Rmisc)
```



```{r get familiar with data, echo=FALSE, message=FALSE}
student <- read_csv("StudentsPerformance.csv")

names(student)<-make.names(names(student),unique = TRUE)
summary(student)
#names(student)
# glimpse(student)
# typeof(student)
# str(student)
 #class(student)
#describe(student)

```


# Descriptive Statistics

```{r, echo=FALSE, message=FALSE}
#range(student$reading.score) (0, 6000)
#range(student$math.score)
studentTable1 <- student %>% 
            group_by(gender) %>%
             summarise(n = nrow(student),
            Average_math = mean(math.score),
            SD_math = sd(math.score),
            min_math = min(math.score),
            max_math = max(math.score))
            
studentTable2 <- student %>% 
            group_by(gender) %>%
            summarise(n = nrow(student),
            Average_reading = mean(reading.score),
            SD_reading = sd(reading.score),
            min_reading = min(reading.score),
            max_reading = max(reading.score))

studentTable3 <- student %>% 
            group_by(gender) %>%
            summarise(n = nrow(student),
            Average_writing = mean(writing.score),
            SD_writing = sd(writing.score),
            min_writing = min(writing.score),
            max_writing = max(writing.score))

                       

datatable(studentTable1)
datatable(studentTable2)
datatable(studentTable3)
```


Math Score
```{r ,echo=FALSE, message=FALSE}
ggplot(student, aes(x = math.score, color = gender)) +
   geom_histogram(bins = 9) +
  geom_vline(aes(xintercept=mean(math.score)),
            color="blue", linetype="dashed", size=1) +
  facet_grid(. ~ gender) +
  coord_cartesian(xlim = c(0,100)) +
  labs(title = "mean & frequency for the math score") +
  theme_classic()+
 NULL

```

writing Score
```{r ,echo=FALSE, message=FALSE}
ggplot(student, aes(x = writing.score, color = gender)) +
   geom_histogram(bins = 9) +
  geom_vline(aes(xintercept=mean(writing.score)),
            color="blue", linetype="dashed", size=1) +
  facet_grid(. ~ gender) +
  coord_cartesian(xlim = c(0,100)) +
  labs(title = "mean & frequency for the writing score") +
  theme_classic()+
 NULL

```

Writing Score
```{r ,echo=FALSE, message=FALSE}
ggplot(student, aes(x = writing.score, color = gender)) +
   geom_histogram(bins = 9) +
  geom_vline(aes(xintercept=mean(writing.score)),
            color="blue", linetype="dashed", size=1) +
  facet_grid(. ~ gender) +
  coord_cartesian(xlim = c(0,100)) +
  labs(title = "mean & frequency for the writing score") +
  theme_classic()+
 NULL

```

# Infrential Statistics 


```{r,echo=FALSE, message=FALSE}
 math_50 <-  sum(student$math.score > 50)
n = nrow(student)
math_50_prob <- (math_50/n)*100
```
The probability for the students to get more than 50 in math is `r math_50_prob`%

```{r,echo=FALSE, message=FALSE}
 writing_50 <-  sum(student$writing.score > 50)
n = nrow(student)
writing_50_prob <- (writing_50/n)*100
```
The probability for the students to get more than 50 in writing is `r writing_50_prob`%

```{r,echo=FALSE, message=FALSE}
 reading_50 <-  sum(student$reading.score > 50)
n = nrow(student)
reading_50_prob <- (reading_50/n)*100
```
The probability for the students to get more than 50 in reading is `r reading_50_prob`%

# Two sample t-test

```{r}
ggplot(student, aes(x = 1, y = math.score)) +
  geom_jitter(width = 0.2) +
  labs(title = "No information from X at all")
```

```{r}
ggplot(student, aes(x = gender, y = math.score, color = gender)) +
  geom_jitter(width = 0.2) +
  labs(title = "ALL information from X that is available")
```
$\bar{x}_{female} - \bar{x}_{male}$
```{r}
t.test(math.score ~ gender, data = student)
```
